modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/mahmudindev/mcmod-desertdimension"
license = "ARR"

[[mods]]
modId = "desertdimension"
version = "${version}"
displayName = "Desert Dimension"
authors = "mahmudindev"
description = '''
Add desert single biome world type as separate dimension.
'''
logoFile = "assets/desertdimension/icon.png"

[[dependencies.desertdimension]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.desertdimension]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.desertdimension]]
modId = "dimensionfixer"
mandatory = true
versionRange = "[0.0.9,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.desertdimension]]
modId = "worldportal"
mandatory = true
versionRange = "[0.0.9,)"
ordering = "NONE"
side = "SERVER"
