modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/mahmudindev/mcmod-desertdimension"
license = "ARR"

[[mods]]
modId = "desertdimension"
version = "${version}"
displayName = "Desert Dimension"
authors = "mahmudindev"
description = '''
Add desert single biome world type as separate dimension.
'''
logoFile = "assets/desertdimension/icon.png"

[[dependencies.desertdimension]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.desertdimension]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.desertdimension]]
modId = "dimensionfixer"
type = "required"
versionRange = "[0.0.9,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.desertdimension]]
modId = "worldportal"
type = "required"
versionRange = "[0.0.9,)"
ordering = "NONE"
side = "SERVER"

[[mixins]]
config = "desertdimension.mixins.json"
